### ISSUE TITLE
tidy_hosts_file getting called constantly

### ISSUE THREAD

**Issue by spoofedpacket** [wyrie/puppet-backuppc#11]
The "tidy_hosts_file" exec appears to get called constantly, I believe this is due to the unless parameter below always returning 1:

` unless  => "test \"$(grep '#puppetmanaged' ${backuppc::params::hosts} | awk '{print \$1}' | sort | perl -pe 'chomp')\" = \"${hostsstr}\"`

Digging a bit further, it looks like puppet's stdlib sort() and GNU sort don't work exactly the same way. So, the content of $hostsstr will always be different to the test being carried out above, thus tidy_hosts_file will always get called.

I did a couple of quick tests and it seems to be related to alphanumeric sorts, so hostnames consisting of names and numbers would cause it. For example, the result of the grep/awk/sort above would be (before the perl chomp):
 
 hostname3.example.com
 hostname2.example.com
 hostname.example

Whereas the data extracted from PuppetDB and then passed through stdlib sort() is:

 hostname.example.com
 hostname2.example.com
 hostname3.example.com

**Comment by spoofedpacket** [comment]
Actually, this looks like a locale issue. If I set LC_COLLATE=C and then run sort, the output matches stdlib sort() (well, ruby's sort internally).

**Comment by wyrie** [comment]
Thanks for opening the issue.

I've pushed a fix but haven't tested it yet. If you run it please let me know if it has solved your problem.

**Comment by spoofedpacket** [comment]
Tested it out just there, looks good - tidy_hosts_file no longer gets called with each puppet run. Thanks!
